# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebrtcPipingTunnel < Formula
  desc "WebRTC tunnel with Piping Server WebRTC signaling"
  homepage "https://github.com/nwtgck/go-webrtc-piping-tunnel"
  version "0.1.0-release-trigger1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger1/webrtc-piping-tunnel-0.1.0-release-trigger1-darwin-arm64.tar.gz"
      sha256 "e54ca87838546486e58c2a62ae4ea3a7254b4feaafbe47987b53fceb78e4e2f8"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger1/webrtc-piping-tunnel-0.1.0-release-trigger1-darwin-amd64.tar.gz"
      sha256 "c87963f4177a34677868c69c1257519f4d49b6252a62dcb94415fb97ddb4a34c"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger1/webrtc-piping-tunnel-0.1.0-release-trigger1-linux-arm64.tar.gz"
      sha256 "90c4c9e288d76638e82848b0e315c2ddf53b80a22f33f40bfefe9c7501c7f0cc"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger1/webrtc-piping-tunnel-0.1.0-release-trigger1-linux-armv6.tar.gz"
      sha256 "e72ae226f41f2d74d6a481962e6fa0a7c2826a60eae94d85a7e970bf99aaf35a"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger1/webrtc-piping-tunnel-0.1.0-release-trigger1-linux-amd64.tar.gz"
      sha256 "f615138be95973d8a140299510d6dab1fd694e5b984243ca8c9494ed4e1c6b6c"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
  end
end
