# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebrtcPipingTunnel < Formula
  desc "WebRTC tunnel with Piping Server WebRTC signaling"
  homepage "https://github.com/nwtgck/go-webrtc-piping-tunnel"
  version "0.1.0-release-trigger2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger2/webrtc-piping-tunnel-0.1.0-release-trigger2-darwin-arm64.tar.gz"
      sha256 "bdf7ca81fc417ea8f7bd82b4b0a7e4411ad18af3199ee06a4d64e0648314d038"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger2/webrtc-piping-tunnel-0.1.0-release-trigger2-darwin-amd64.tar.gz"
      sha256 "32d98662e4cee8ff8db12563119a8972b9f6ef952951a96a76046f13949638bb"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger2/webrtc-piping-tunnel-0.1.0-release-trigger2-linux-amd64.tar.gz"
      sha256 "7bc574bfcaefd94596c72b39d119ad94acde42c2bafdd2697adf2bda4f37884c"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger2/webrtc-piping-tunnel-0.1.0-release-trigger2-linux-armv6.tar.gz"
      sha256 "ea865e05cbb85de1fee3c7302fd19a2561a928f4ea232947355aec78ce70063a"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-webrtc-piping-tunnel/releases/download/v0.1.0-release-trigger2/webrtc-piping-tunnel-0.1.0-release-trigger2-linux-arm64.tar.gz"
      sha256 "fcdf063ed99b1b6895879393dc8285cfcf021174f4574a60dc62209571fd7108"

      def install
        bin.install "webrtc-piping-tunnel"
      end
    end
  end
end
